version: '2'
volumes:
  rsync-volume:
    driver: local
services:
  openttd-rsync:
    image: joshhsoj1902/ogp-custom-rsync-games
    restart: always
    volumes:
      - rsync-volume:/srv/games
    command: ["perl", "RunUpdate.pl", "update", "openttd"]
  openttd-agent:
    image: joshhsoj1902/docker-ogpagent
    restart: always
    volumes:
      - rsync-volume:/srv/games
    working_dir: /srv/games/openttd/linux
    command: ["./openttd"]

  # agent:
  #   image: joshhsoj1902/docker-ogpagent
  #   restart: always
  #   ports:
  #     - "12679:12679/tcp"
  #     - "27015:27015/tcp"
  #     - "27015:27015/udp"
  #   volumes:
  #     - ./ogp_agent/games:/home/ogp_agent/OGP_User_Files
  #     - ./ogp_agent/Cfg:/opt/OGP/Cfg
  #     - ./ogp_agent/stemcmd:/opt/OGP/steamcmd
