version: 2
jobs:
  build:
    working_directory: ~/ogp
    machine: true
    steps:
      - checkout
      - run:
          name: "Build Image"
          command: |
            make build
      - run:
          name: ""
          command: |
            ./update_games.sh update all
